package com.felit.drools.chapter01
import java.util.Date
declare Requirement
   title: String
   content: String
   handled_at: Date
   created_at: Date
   last_updated: Date
end

rule "the requirements to handle"
dialect "java"
when
    $r : Requirement()
then
   System.out.println($r + "");
   // Retraction is the removal of a fact from Working Memory,
   // which means that it will no longer track and match that fact,
   // and any rules that are activated and dependent on that fact will be cancelled.
   retract($r)
end